In [13]:
# how to import pandas in python 

import pandas as pd

In [14]:
# how to read csv file in pandas
# how to give path in jupyter notebook if you are working in mac to run a csv file in pandas

df = pd.read_csv('~/Desktop/CSV Files/weather 2.csv')

In [15]:
df

,EST,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,WindDir3pm,...,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RISK_MM,RainTomorrow
0,1/1/2016,8.0,24.3,0.0,3.4,6.3,NW,30.0,SW,NW,...,29,1019.7,1015.0,7,7,14.4,23.6,No,3.6,Yes
1,2/1/2016,14.0,26.9,3.6,4.4,9.7,ENE,39.0,E,W,...,36,1012.4,1008.4,5,3,17.5,25.7,Yes,3.6,Yes
2,3/1/2016,13.7,23.4,3.6,5.8,3.3,NW,85.0,N,NNE,...,69,1009.5,1007.2,8,7,15.4,20.2,Yes,39.8,Yes
3,4/1/2016,13.3,15.5,39.8,7.2,9.1,NW,54.0,WNW,W,...,56,1005.5,1007.0,2,7,13.5,14.1,Yes,2.8,Yes
4,5/1/2016,7.6,16.1,2.8,5.6,10.6,SSE,50.0,SSE,ESE,...,49,1018.3,1018.5,7,7,11.1,15.4,Yes,0.0,No
5,6/1/2016,6.2,16.9,0.0,5.8,8.2,SE,44.0,SE,E,...,57,1023.8,1021.7,7,5,10.9,14.8,No,0.2,No
6,7/1/2016,6.1,18.2,0.2,4.2,8.4,SE,43.0,SE,ESE,...,47,1024.6,1022.2,4,6,12.4,17.3,No,0.0,No
7,8/1/2016,8.3,17.0,0.0,5.6,4.6,E,41.0,SE,E,...,57,1026.2,1024.2,6,7,12.1,15.5,No,0.0,No
8,9/1/2016,8.8,19.5,0.0,4.0,4.1,S,48.0,E,ENE,...,48,1026.1,1022.7,7,7,14.1,18.9,No,16.2,Yes
9,10/1/2016,8.4,22.8,16.2,5.4,7.7,E,31.0,S,ESE,...,32,1024.1,1020.7,7,1,13.3,21.7,Yes,0.0,No
10,11/1/2016,9.1,25.2,0.0,4.2,11.9,N,30.0,SE,NW,...,34,1024.4,1021.1,1,2,14.6,24.0,No,0.2,No
11,12/1/2016,8.5,27.3,0.2,7.2,12.5,E,41.0,E,NW,...,35,1023.8,1019.9,0,3,16.8,26.0,No,0.0,No
12,13/1/2016,10.1,27.9,0.0,7.2,13.0,WNW,30.0,S,NW,...,29,1022.0,1017.1,0,1,17.0,27.1,No,0.0,No
13,14/1/2016,12.1,30.9,0.0,6.2,12.4,NW,44.0,WNW,W,...,20,1017.3,1013.1,1,4,19.7,30.7,No,0.0,No
14,15/1/2016,10.1,31.2,0.0,8.8,13.1,NW,41.0,S,W,...,16,1018.2,1013.7,0,1,18.7,30.4,No,0.0,No
15,16/1/2016,12.4,32.1,0.0,8.4,11.1,E,46.0,SE,WSW,...,22,1017.9,1012.8,0,3,19.1,30.7,No,0.0,No
16,17/1/2016,13.8,31.2,0.0,7.2,8.4,ESE,44.0,WSW,W,...,23,1014.4,1009.8,7,6,20.2,29.8,No,1.2,Yes
17,18/1/2016,11.7,30.0,1.2,7.2,10.1,S,52.0,SW,NE,...,26,1016.4,1013.0,1,5,20.1,28.6,Yes,0.6,No
18,19/1/2016,12.4,32.3,0.6,7.4,13.0,E,39.0,NNE,W,...,25,1017.1,1013.3,1,3,20.2,31.2,No,0.0,No
19,20/1/2016,15.6,33.4,0.0,8.0,10.4,NE,33.0,NNW,NNW,...,27,1018.5,1013.7,0,1,22.8,32.0,No,0.0,No
20,21/1/2016,15.3,33.4,0.0,8.8,9.5,WNW,59.0,N,NW,...,26,1012.4,1006.5,1,5,22.2,32.8,No,0.4,No
21,22/1/2016,16.4,19.4,0.4,9.2,0.0,E,26.0,ENE,E,...,72,1010.7,1008.9,8,8,16.5,18.3,No,25.8,Yes
22,23/1/2016,12.8,18.5,25.8,2.8,0.6,ESE,28.0,S,SE,...,79,1014.0,1014.9,8,8,14.0,16.8,Yes,0.4,No
23,24/1/2016,12.0,24.3,0.4,1.2,7.5,NNE,26.0,WSW,NE,...,57,1020.7,1019.2,7,5,17.8,22.8,No,0.0,No
24,25/1/2016,15.4,28.4,0.0,4.4,8.1,ENE,33.0,SSE,NE,...,31,1022.4,1018.6,8,2,16.8,27.3,No,0.0,No
25,26/1/2016,15.6,26.9,0.0,6.8,8.9,E,41.0,E,E,...,48,1019.7,1016.5,2,4,19.8,25.1,No,0.2,No
26,27/1/2016,13.3,22.2,0.2,6.6,2.3,ENE,39.0,E,E,...,55,1021.0,1018.6,7,7,16.5,21.2,No,0.0,No
27,28/1/2016,12.9,28.0,0.0,4.4,10.7,S,52.0,S,NNE,...,31,1019.2,1014.8,5,7,18.8,26.7,No,0.0,No
28,29/1/2016,15.1,24.3,0.0,7.0,0.4,SE,39.0,SE,SE,...,80,1019.0,1017.1,7,7,18.9,19.7,No,0.4,No
29,30/1/2016,13.6,24.1,0.4,2.6,0.5,NNW,30.0,SSW,S,...,49,1017.2,1013.3,8,7,17.3,23.2,No,22.6,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
336,2/12/2016,5.6,27.6,0.0,5.2,11.0,NW,46.0,NNW,NW,...,21,1017.7,1014.1,0,0,19.0,26.7,No,0.0,No
337,3/12/2016,16.8,28.9,0.0,10.0,10.8,NNW,70.0,NW,NW,...,22,1016.3,1011.8,1,1,22.5,28.4,No,7.6,Yes
338,4/12/2016,14.4,20.7,7.6,9.4,4.9,NNW,33.0,NNW,NNW,...,65,1015.5,1013.2,8,4,14.5,19.3,Yes,3.0,Yes
339,5/12/2016,10.3,21.3,3.0,4.2,6.7,NNW,43.0,ENE,N,...,46,1018.1,1013.6,8,1,11.7,19.8,Yes,0.0,No
340,6/12/2016,11.2,18.0,0.0,4.8,8.4,W,65.0,N,W,...,40,1009.5,1005.3,5,4,12.8,16.2,No,8.2,Yes
341,7/12/2016,0.3,16.0,8.2,5.4,11.8,NW,57.0,NNW,N,...,45,1016.8,1013.3,1,1,6.9,14.6,Yes,0.0,No
342,8/12/2016,0.5,17.9,0.0,5.8,11.5,N,44.0,NNE,NNW,...,33,1019.1,1017.5,0,1,7.2,16.6,No,0.0,No
343,9/12/2016,0.5,20.0,0.0,6.2,11.5,NNW,31.0,S,N,...,22,1026.2,1024.2,0,1,8.1,18.8,No,0.0,No
344,10/12/2016,4.6,22.0,0.0,4.4,11.0,N,41.0,NNW,N,...,25,1028.8,1024.9,1,2,10.0,21.4,No,0.0,No
345,11/12/2016,8.2,22.4,0.0,5.4,11.2,NW,31.0,SSW,NW,...,30,1027.8,1023.8,1,3,13.6,20.6,No,0.0,No
346,12/12/2016,4.5,23.9,0.0,4.8,11.7,NW,30.0,ENE,NNW,...,27,1025.8,1021.5,0,4,12.6,22.3,No,0.0,No
347,13/12/2016,6.7,26.1,0.0,6.2,7.5,SSW,70.0,NE,NNW,...,47,1020.9,1016.0,4,7,16.3,23.2,No,13.2,Yes
348,14/12/2016,11.9,21.1,13.2,6.6,NaN,NW,41.0,NNE,N,...,61,1019.2,1016.7,7,3,14.5,19.4,Yes,0.6,No
349,15/12/2016,9.2,19.6,0.6,3.4,10.4,ENE,31.0,SSE,NNW,...,42,1022.3,1019.7,7,4,11.6,18.4,No,0.0,No
350,16/12/2016,4.4,21.0,0.0,4.2,12.2,NW,28.0,SW,NW,...,30,1025.7,1022.3,1,1,9.6,19.2,No,0.0,No
351,17/12/2016,5.0,24.1,0.0,6.2,12.0,NNW,52.0,NaN,NNW,...,34,1024.5,1020.7,6,1,11.6,21.9,No,0.0,No
352,18/12/2016,6.7,24.7,0.0,5.4,8.6,NW,43.0,N,NW,...,31,1025.7,1022.2,1,7,12.7,23.7,No,0.0,No
353,19/12/2016,8.3,28.5,0.0,5.8,9.8,NW,46.0,W,NW,...,30,1024.1,1019.8,1,6,16.8,27.4,No,0.2,No
354,20/12/2016,11.3,27.4,0.2,7.6,12.1,NW,52.0,SE,NW,...,20,1021.4,1017.5,1,1,16.4,26.3,No,0.0,No
355,21/12/2016,9.0,20.6,0.0,9.0,6.2,ENE,39.0,S,SW,...,28,1022.3,1018.6,7,5,11.4,18.5,No,0.8,No
356,22/12/2016,3.4,15.0,0.8,4.8,11.7,S,70.0,S,S,...,24,1023.4,1023.1,1,5,8.3,14.3,No,0.0,No
357,23/12/2016,3.2,18.0,0.0,7.4,12.2,SSE,48.0,SSE,S,...,25,1026.6,1022.8,1,2,9.1,16.3,No,0.0,No
358,24/12/2016,0.9,20.7,0.0,5.4,8.4,NNW,39.0,SSE,N,...,29,1023.2,1018.4,3,8,9.4,19.1,No,0.0,No
359,25/12/2016,3.3,25.5,0.0,5.2,10.8,N,43.0,N,NNW,...,16,1018.8,1014.6,0,3,12.0,24.8,No,0.0,No
360,26/12/2016,7.9,26.1,0.0,6.8,3.5,NNW,43.0,NaN,WNW,...,20,1017.6,1014.2,5,8,16.3,25.9,No,0.0,No
361,27/12/2016,9.0,30.7,0.0,7.6,12.1,NNW,76.0,SSE,NW,...,15,1016.1,1010.8,1,3,20.4,30.0,No,0.0,No
362,28/12/2016,7.1,28.4,0.0,11.6,12.7,N,48.0,NNW,NNW,...,22,1020.0,1016.9,0,1,17.2,28.2,No,0.0,No
363,29/12/2016,12.5,19.9,0.0,8.4,5.3,ESE,43.0,ENE,ENE,...,47,1024.0,1022.8,3,2,14.5,18.3,No,0.0,No
364,30/12/2016,12.5,26.9,0.0,5.0,7.1,NW,46.0,SSW,WNW,...,39,1021.0,1016.2,6,7,15.8,25.9,No,0.0,No
365,31/12/2016,12.3,30.2,0.0,6.0,12.6,NW,78.0,NW,WNW,...,13,1009.6,1009.2,1,1,23.8,28.6,No,0.0,No

In [16]:
# how to print first five rows
df.head()

,EST,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,WindDir3pm,...,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RISK_MM,RainTomorrow
0,1/1/2016,8.0,24.3,0.0,3.4,6.3,NW,30.0,SW,NW,...,29,1019.7,1015.0,7,7,14.4,23.6,No,3.6,Yes
1,2/1/2016,14.0,26.9,3.6,4.4,9.7,ENE,39.0,E,W,...,36,1012.4,1008.4,5,3,17.5,25.7,Yes,3.6,Yes
2,3/1/2016,13.7,23.4,3.6,5.8,3.3,NW,85.0,N,NNE,...,69,1009.5,1007.2,8,7,15.4,20.2,Yes,39.8,Yes
3,4/1/2016,13.3,15.5,39.8,7.2,9.1,NW,54.0,WNW,W,...,56,1005.5,1007.0,2,7,13.5,14.1,Yes,2.8,Yes
4,5/1/2016,7.6,16.1,2.8,5.6,10.6,SSE,50.0,SSE,ESE,...,49,1018.3,1018.5,7,7,11.1,15.4,Yes,0.0,No

In [17]:
# how to print last five rows
df.tail()

,EST,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,WindDir3pm,...,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RISK_MM,RainTomorrow
361,27/12/2016,9.0,30.7,0.0,7.6,12.1,NNW,76.0,SSE,NW,...,15,1016.1,1010.8,1,3,20.4,30.0,No,0.0,No
362,28/12/2016,7.1,28.4,0.0,11.6,12.7,N,48.0,NNW,NNW,...,22,1020.0,1016.9,0,1,17.2,28.2,No,0.0,No
363,29/12/2016,12.5,19.9,0.0,8.4,5.3,ESE,43.0,ENE,ENE,...,47,1024.0,1022.8,3,2,14.5,18.3,No,0.0,No
364,30/12/2016,12.5,26.9,0.0,5.0,7.1,NW,46.0,SSW,WNW,...,39,1021.0,1016.2,6,7,15.8,25.9,No,0.0,No
365,31/12/2016,12.3,30.2,0.0,6.0,12.6,NW,78.0,NW,WNW,...,13,1009.6,1009.2,1,1,23.8,28.6,No,0.0,No

In [18]:
# how many rows and colums are there in a dataframe? 
df.shape
# the above dataframe has 366 rows and 23 columns

(366, 23)

In [24]:
# if you want to print either rows or column?
rows, columns = df.shape
rows

366

In [25]:
columns

23

In [20]:
# for some further information
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 366 entries, 0 to 365
Data columns (total 23 columns):
EST              366 non-null object
MinTemp          366 non-null float64
MaxTemp          366 non-null float64
Rainfall         366 non-null float64
Evaporation      366 non-null float64
Sunshine         363 non-null float64
WindGustDir      363 non-null object
WindGustSpeed    364 non-null float64
WindDir9am       335 non-null object
WindDir3pm       365 non-null object
WindSpeed9am     359 non-null float64
WindSpeed3pm     366 non-null int64
Humidity9am      366 non-null int64
Humidity3pm      366 non-null int64
Pressure9am      366 non-null float64
Pressure3pm      366 non-null float64
Cloud9am         366 non-null int64
Cloud3pm         366 non-null int64
Temp9am          366 non-null float64
Temp3pm          366 non-null float64
RainToday        366 non-null object
RISK_MM          366 non-null float64
RainTomorrow     366 non-null object
dtypes: float64(12), int64(5), object(6)
memory usage: 65.8+ KB

In [22]:
# to know statistics of your data
df.describe()

,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustSpeed,WindSpeed9am,WindSpeed3pm,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RISK_MM
count,366.000000,366.000000,366.000000,366.000000,363.000000,364.000000,359.000000,366.000000,366.000000,366.000000,366.000000,366.000000,366.000000,366.000000,366.000000,366.000000,366.000000
mean,7.265574,20.550273,1.428415,4.521858,7.909366,39.840659,9.651811,17.986339,72.035519,44.519126,1019.709016,1016.810383,3.890710,4.024590,12.358470,19.230874,1.428415
std,6.025800,6.690516,4.225800,2.669383,3.481517,13.059807,7.951929,8.856997,13.137058,16.850947,6.686212,6.469422,2.956131,2.666268,5.630832,6.640346,4.225800
min,-5.300000,7.600000,0.000000,0.200000,0.000000,13.000000,0.000000,0.000000,36.000000,13.000000,996.500000,996.800000,0.000000,0.000000,0.100000,5.100000,0.000000
25%,2.300000,15.025000,0.000000,2.200000,5.950000,31.000000,6.000000,11.000000,64.000000,32.250000,1015.350000,1012.800000,1.000000,1.000000,7.625000,14.150000,0.000000
50%,7.450000,19.650000,0.000000,4.200000,8.600000,39.000000,7.000000,17.000000,72.000000,43.000000,1020.150000,1017.400000,3.500000,4.000000,12.550000,18.550000,0.000000
75%,12.500000,25.500000,0.200000,6.400000,10.500000,46.000000,13.000000,24.000000,81.000000,55.000000,1024.475000,1021.475000,7.000000,7.000000,17.000000,24.000000,0.200000
max,20.900000,35.800000,39.800000,13.800000,13.600000,98.000000,41.000000,52.000000,99.000000,96.000000,1035.700000,1033.200000,8.000000,8.000000,24.700000,34.500000,39.800000

In [26]:
# indexing and slicing the DataFrame
df[2:6]
# it will include 2 but does not include 6

,EST,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,WindDir3pm,...,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RISK_MM,RainTomorrow
2,3/1/2016,13.7,23.4,3.6,5.8,3.3,NW,85.0,N,NNE,...,69,1009.5,1007.2,8,7,15.4,20.2,Yes,39.8,Yes
3,4/1/2016,13.3,15.5,39.8,7.2,9.1,NW,54.0,WNW,W,...,56,1005.5,1007.0,2,7,13.5,14.1,Yes,2.8,Yes
4,5/1/2016,7.6,16.1,2.8,5.6,10.6,SSE,50.0,SSE,ESE,...,49,1018.3,1018.5,7,7,11.1,15.4,Yes,0.0,No
5,6/1/2016,6.2,16.9,0.0,5.8,8.2,SE,44.0,SE,E,...,57,1023.8,1021.7,7,5,10.9,14.8,No,0.2,No

In [27]:
# if you want to know the column names
df.columns

Index(['EST', 'MinTemp', 'MaxTemp', 'Rainfall', 'Evaporation', 'Sunshine',
       'WindGustDir', 'WindGustSpeed', 'WindDir9am', 'WindDir3pm',
       'WindSpeed9am', 'WindSpeed3pm', 'Humidity9am', 'Humidity3pm',
       'Pressure9am', 'Pressure3pm', 'Cloud9am', 'Cloud3pm', 'Temp9am',
       'Temp3pm', 'RainToday', 'RISK_MM', 'RainTomorrow'],
      dtype='object')

In [28]:
# if you want to know the type of your column
type(df['EST'])
# Hence Columns in a DataFrame is of Series type.

pandas.core.series.Series

In [30]:
#if you want to print series in a DataFrame
df['MinTemp'].head()

0     8.0
1    14.0
2    13.7
3    13.3
4     7.6
Name: MinTemp, dtype: float64

In [32]:
# if you want to print DataFrame with one column only
df[['MinTemp']].head()

   MinTemp
0      8.0
1     14.0
2     13.7
3     13.3
4      7.6

In [33]:
# if you want to print any column of your choice from the DataFrame
df[['MinTemp','WindGustSpeed']].head()

   MinTemp  WindGustSpeed
0      8.0           30.0
1     14.0           39.0
2     13.7           85.0
3     13.3           54.0
4      7.6           50.0

In [38]:
# if you want to set any column as a index
df.set_index('EST', inplace = True).head()
# We use inplace  = True to update the changes in the DataFrame

,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,WindDir3pm,WindSpeed9am,...,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RISK_MM,RainTomorrow
EST,,,,,,,,,,,,,,,,,,,,,
1/1/2016,8.0,24.3,0.0,3.4,6.3,NW,30.0,SW,NW,6.0,...,29,1019.7,1015.0,7,7,14.4,23.6,No,3.6,Yes
2/1/2016,14.0,26.9,3.6,4.4,9.7,ENE,39.0,E,W,4.0,...,36,1012.4,1008.4,5,3,17.5,25.7,Yes,3.6,Yes
3/1/2016,13.7,23.4,3.6,5.8,3.3,NW,85.0,N,NNE,6.0,...,69,1009.5,1007.2,8,7,15.4,20.2,Yes,39.8,Yes
4/1/2016,13.3,15.5,39.8,7.2,9.1,NW,54.0,WNW,W,30.0,...,56,1005.5,1007.0,2,7,13.5,14.1,Yes,2.8,Yes
5/1/2016,7.6,16.1,2.8,5.6,10.6,SSE,50.0,SSE,ESE,20.0,...,49,1018.3,1018.5,7,7,11.1,15.4,Yes,0.0,No

In [47]:
# if you want to reset your index as it was before
df.reset_index
df.head()

,level_0,index,EST,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,...,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RISK_MM,RainTomorrow
0,0,0,1/1/2016,8.0,24.3,0.0,3.4,6.3,NW,30.0,...,29,1019.7,1015.0,7,7,14.4,23.6,No,3.6,Yes
1,1,1,2/1/2016,14.0,26.9,3.6,4.4,9.7,ENE,39.0,...,36,1012.4,1008.4,5,3,17.5,25.7,Yes,3.6,Yes
2,2,2,3/1/2016,13.7,23.4,3.6,5.8,3.3,NW,85.0,...,69,1009.5,1007.2,8,7,15.4,20.2,Yes,39.8,Yes
3,3,3,4/1/2016,13.3,15.5,39.8,7.2,9.1,NW,54.0,...,56,1005.5,1007.0,2,7,13.5,14.1,Yes,2.8,Yes
4,4,4,5/1/2016,7.6,16.1,2.8,5.6,10.6,SSE,50.0,...,49,1018.3,1018.5,7,7,11.1,15.4,Yes,0.0,No